"""add cor_carro, servicos, atendimento_servicos table

Revision ID: 069ccdf412bb
Revises: 8049f71fd96d
Create Date: 2026-07-30 10:10:58.659320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '069ccdf412bb'
down_revision: Union[str, Sequence[str], None] = '8049f71fd96d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atendimento_servicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=False),
    sa.Column('servico', sa.String(length=80), nullable=False),
    sa.Column('concluido', sa.Boolean(), nullable=False),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.Column('concluido_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.ForeignKeyConstraint(['concluido_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atendimento_servicos_atendimento_id'), 'atendimento_servicos', ['atendimento_id'], unique=False)
    op.create_index(op.f('ix_atendimento_servicos_id'), 'atendimento_servicos', ['id'], unique=False)
    op.add_column('clientes', sa.Column('cor_carro', sa.String(length=40), nullable=True))
    op.add_column('clientes', sa.Column('servicos', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'servicos')
    op.drop_column('clientes', 'cor_carro')
    op.drop_index(op.f('ix_atendimento_servicos_id'), table_name='atendimento_servicos')
    op.drop_index(op.f('ix_atendimento_servicos_atendimento_id'), table_name='atendimento_servicos')
    op.drop_table('atendimento_servicos')
    # ### end Alembic commands ###
