"""create lavagens table

Revision ID: 6e5f915238ac
Revises: f7b2e4a1c9d0
Create Date: 2026-07-31 04:02:33.169982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6e5f915238ac'
down_revision: Union[str, Sequence[str], None] = 'f7b2e4a1c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lavagens',
    sa.Column('id_lavagem', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.String(length=20), nullable=False),
    sa.Column('cliente', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=False),
    sa.Column('tipo_carro', sa.String(length=30), nullable=False),
    sa.Column('funcionario_lavagem', sa.String(length=255), nullable=False),
    sa.Column('t_teto_vidros_min', sa.Float(), nullable=False),
    sa.Column('t_capo_parabrisa_min', sa.Float(), nullable=False),
    sa.Column('t_laterais_portas_min', sa.Float(), nullable=False),
    sa.Column('t_traseira_min', sa.Float(), nullable=False),
    sa.Column('t_rodas_pneus_min', sa.Float(), nullable=False),
    sa.Column('t_interior_min', sa.Float(), nullable=False),
    sa.Column('tempo_lavagem_total_min', sa.Float(), nullable=False),
    sa.Column('tempo_espera_antes_lavagem_min', sa.Integer(), nullable=False),
    sa.Column('tempo_pos_lavagem_ate_retirada_min', sa.Integer(), nullable=False),
    sa.Column('tempo_ate_pagamento_min', sa.Integer(), nullable=False),
    sa.Column('atendente_pagamento', sa.String(length=255), nullable=False),
    sa.Column('cnpj_receita', sa.String(length=255), nullable=False),
    sa.Column('metodo_pagamento', sa.String(length=30), nullable=False),
    sa.Column('preco_reais', sa.Float(), nullable=False),
    sa.Column('nps_cliente', sa.Integer(), nullable=False),
    sa.Column('nota_google', sa.Float(), nullable=False),
    sa.Column('shampoo_ml', sa.Integer(), nullable=False),
    sa.Column('cera_ml', sa.Integer(), nullable=False),
    sa.Column('pretinho_ml', sa.Integer(), nullable=False),
    sa.Column('aromatizante_ml', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_lavagem')
    )
    op.create_index(op.f('ix_lavagens_ano'), 'lavagens', ['ano'], unique=False)
    op.create_index(op.f('ix_lavagens_data'), 'lavagens', ['data'], unique=False)
    op.create_index(op.f('ix_lavagens_mes'), 'lavagens', ['mes'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lavagens_mes'), table_name='lavagens')
    op.drop_index(op.f('ix_lavagens_data'), table_name='lavagens')
    op.drop_index(op.f('ix_lavagens_ano'), table_name='lavagens')
    op.drop_table('lavagens')
    # ### end Alembic commands ###
