"""add placa, fotos_atendimento table

Revision ID: 8049f71fd96d
Revises: c9c937ceb983
Create Date: 2026-07-29 15:13:23.814489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8049f71fd96d'
down_revision: Union[str, Sequence[str], None] = 'c9c937ceb983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fotos_atendimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=False),
    sa.Column('momento', sa.Enum('inicio', 'fim', name='momento_foto'), nullable=False),
    sa.Column('dados', sa.LargeBinary(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('registrada_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('registrada_por_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.ForeignKeyConstraint(['registrada_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fotos_atendimento_atendimento_id'), 'fotos_atendimento', ['atendimento_id'], unique=False)
    op.create_index(op.f('ix_fotos_atendimento_id'), 'fotos_atendimento', ['id'], unique=False)
    op.add_column('clientes', sa.Column('placa', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'placa')
    op.drop_index(op.f('ix_fotos_atendimento_id'), table_name='fotos_atendimento')
    op.drop_index(op.f('ix_fotos_atendimento_atendimento_id'), table_name='fotos_atendimento')
    op.drop_table('fotos_atendimento')
    # ### end Alembic commands ###
