"""add termo_aceito_em to atendimentos

Revision ID: ce89483d2f10
Revises: 069ccdf412bb
Create Date: 2026-07-30 13:50:03.039017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce89483d2f10'
down_revision: Union[str, Sequence[str], None] = '069ccdf412bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atendimentos', sa.Column('termo_aceito_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('atendimentos', 'termo_aceito_em')
    # ### end Alembic commands ###
