"""create agendamentos table

Revision ID: d41f9a7c2b3e
Revises: fa005aea78e1
Create Date: 2026-07-30 22:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd41f9a7c2b3e'
down_revision: Union[str, Sequence[str], None] = 'fa005aea78e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('sobrenome', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=False),
    sa.Column('modelo_carro', sa.String(length=255), nullable=False),
    sa.Column('servicos', sa.JSON(), nullable=False),
    sa.Column('preco_total', sa.Float(), nullable=False),
    sa.Column('data', sa.String(length=10), nullable=False),
    sa.Column('horario_inicio', sa.String(length=5), nullable=False),
    sa.Column('horario_fim', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='confirmado', nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendamentos_data'), 'agendamentos', ['data'], unique=False)
    op.create_index(op.f('ix_agendamentos_id'), 'agendamentos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agendamentos_id'), table_name='agendamentos')
    op.drop_index(op.f('ix_agendamentos_data'), table_name='agendamentos')
    op.drop_table('agendamentos')
    # ### end Alembic commands ###
