"""add placa to agendamentos

Revision ID: f7b2e4a1c9d0
Revises: d41f9a7c2b3e
Create Date: 2026-07-31 09:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b2e4a1c9d0'
down_revision: Union[str, Sequence[str], None] = 'd41f9a7c2b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendamentos', sa.Column('placa', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agendamentos', 'placa')
    # ### end Alembic commands ###
