"""add termo_cpf, termo_tem_plano, termo_plano to atendimentos

Revision ID: fa005aea78e1
Revises: ce89483d2f10
Create Date: 2026-07-30 14:06:00.867987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa005aea78e1'
down_revision: Union[str, Sequence[str], None] = 'ce89483d2f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atendimentos', sa.Column('termo_cpf', sa.String(length=20), nullable=True))
    op.add_column('atendimentos', sa.Column('termo_tem_plano', sa.Boolean(), nullable=True))
    op.add_column('atendimentos', sa.Column('termo_plano', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('atendimentos', 'termo_plano')
    op.drop_column('atendimentos', 'termo_tem_plano')
    op.drop_column('atendimentos', 'termo_cpf')
    # ### end Alembic commands ###
